apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci1yZWdpc3RyeS5hLWRldi5jb20vdjEvIjp7InVzZXJuYW1lIjoiYW50eCIsInBhc3N3b3JkIjoiUXdlMzQ0SmtsbGQwOSIsImF1dGgiOiJZVzUwZURwUmQyVXpORFJLYTJ4c1pEQTUifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-private-reg
type: kubernetes.io/dockerconfigjson
